[workspace]
resolver = "2"
members = ["api", "program"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
homepage = ""
documentation = ""
repository = ""
readme = "./README.md"
keywords = ["solana"]

[workspace.dependencies]
hand-api = { path = "./api", version = "0.1.0" }
lever-api = { path = "../lever/api", version = "0.1.0" }
lever-program = { path = "../lever/program", version = "0.1.0", features = [
    "cpi",
] }
bytemuck = "1.14"
num_enum = "0.7"
solana-program = "2.1.21"
steel = "2.0"
thiserror = "1.0"
