[package]
name = "favorites-program"
version = "0.1.0"
description = "Favorites Solana Program(Native)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
borsh = "0.10.3"
solana-program = "1.16.24"
