[package]
name = "token-2022-mint-close-authority-program"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "=2.0.2"
spl-associated-token-account = { version="4.0.0", features = [ "no-entrypoint" ] }
spl-token-2022 = {version = "4.0.0", features = [ "no-entrypoint" ] }

[lib]
crate-type = ["cdylib", "lib"]
