[package]
name = "create-token-program"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
create-token-api.workspace = true
solana-program.workspace = true
steel.workspace = true
spl-token.workspace = true
mpl-token-metadata.workspace = true

[dev-dependencies]
base64 = "0.21"
rand = "0.8.5"
solana-program-test = "1.18"
solana-sdk = "1.18"
tokio = { version = "1.35", features = ["full"] }
