[package]
name = "hello-solana-program-pinocchio"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio.workspace = true
pinocchio-log.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
custom-heap = []
custom-panic = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
