[package]
name = "cross-program-invocation-pinocchio-hand"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]
custom-heap = []
custom-panic = []

[dependencies]
pinocchio = "0.9.2"
pinocchio-log = "0.5.1"
pinocchio-system = "0.4.0"

[lib]
crate-type = ["cdylib", "lib"]

[dev-dependencies]
litesvm = "0.8.1"
solana-instruction = "3.0.0"
solana-keypair = "3.0.1"
solana-native-token = "3.0.0"
solana-pubkey = "3.0.0"
solana-transaction = "3.0.1"
solana-system-interface = {version = "2.0.0", features = ["bincode"]}

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
