name: Seahorse Programs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
      container:
        image: docker.io/solanadevelopers/solana-workshop-image-seahorse
        credentials:
          username: solanadevelopers
          password: ${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}
    strategy:
      matrix:
        {
          dir:
            [
              "basics/counter/seahorse",
              "basics/hello-solana/seahorse",
              "basics/transfer-sol/seahorse",
            ],
        }

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build program
        working-directory: ${{ matrix.dir }}
        run: cargo build-sbf --verbose
